=== lumig242/VisTrailsRecommendation/vistrails_current/vistrails/db/versions/v1_0_3/schemas/xml/vistrail.xsd
<!--###############################################################################
##
## Copyright (C) 2011-2014, NYU-Poly.
## Copyright (C) 2006-2011, University of Utah. 
## All rights reserved.
## Contact: contact@vistrails.org
##
## This file is part of VisTrails.
##
## "Redistribution and use in source and binary forms, with or without 
## modification, are permitted provided that the following conditions are met:
##
##  - Redistributions of source code must retain the above copyright notice, 
##    this list of conditions and the following disclaimer.
##  - Redistributions in binary form must reproduce the above copyright 
##    notice, this list of conditions and the following disclaimer in the 
##    documentation and/or other materials provided with the distribution.
##  - Neither the name of the University of Utah nor the names of its 
##    contributors may be used to endorse or promote products derived from 
##    this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
## AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
## THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
## PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
## CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
## EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
## PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
## OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
## WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
## OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
## ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
##
###############################################################################
-->

<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="vistrail">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="action" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="tag" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="vistrailVariable" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="parameter_exploration" ref="parameterExploration" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="actionAnnotation" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="version" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="action">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice>
          <xs:element ref="add" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="delete" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="change" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="prevId" type="xs:int"/>
      <xs:attribute name="date" type="xs:dateTime"/>
      <xs:attribute name="session" type="xs:int"/>
      <xs:attribute name="user" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tag">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="annotation">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="key" type="xs:string"/>
      <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="vistrailVariable">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="uuid" type="xs:string"/>
      <xs:attribute name="package" type="xs:string"/>
      <xs:attribute name="module" type="xs:string"/>
      <xs:attribute name="namespace" type="xs:string"/>
      <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameterExploration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="function" ref="peFunction" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="actionId" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="date" type="xs:dateTime"/>
      <xs:attribute name="user" type="xs:string"/>
      <xs:attribute name="dims" type="xs:string"/>
      <xs:attribute name="layout" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="actionAnnotation">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="key" type="xs:string"/>
      <xs:attribute name="value" type="xs:string"/>
      <xs:attribute name="actionId" type="xs:int"/>
      <xs:attribute name="date" type="xs:dateTime"/>
      <xs:attribute name="user" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="add">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="module" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="connection" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="port" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="portSpec" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="abstraction" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="group" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="other" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="plugin_data" minOccurs="0" maxOccurs="1"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="what" type="xs:string"/>
      <xs:attribute name="objectId" type="xs:int"/>
      <xs:attribute name="parentObjId" type="xs:int"/>
      <xs:attribute name="parentObjType" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="delete">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="what" type="xs:string"/>
      <xs:attribute name="objectId" type="xs:int"/>
      <xs:attribute name="parentObjId" type="xs:int"/>
      <xs:attribute name="parentObjType" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="change">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="module" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="connection" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="port" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="portSpec" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="abstraction" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="group" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="other" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="plugin_data" minOccurs="0" maxOccurs="1"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="what" type="xs:string"/>
      <xs:attribute name="oldObjId" type="xs:int"/>
      <xs:attribute name="newObjId" type="xs:int"/>
      <xs:attribute name="parentObjId" type="xs:int"/>
      <xs:attribute name="parentObjType" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="peFunction">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="parameter" ref="peParameter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="moduleId" type="xs:int"/>
      <xs:attribute name="port_name" type="xs:string"/>
      <xs:attribute name="is_alias" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="module">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="portSpec" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="cache" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="namespace" type="xs:string"/>
      <xs:attribute name="package" type="xs:string"/>
      <xs:attribute name="version" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="location">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="x" type="xs:float"/>
      <xs:attribute name="y" type="xs:float"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="pos" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="connection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="port" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="port">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="moduleId" type="xs:int"/>
      <xs:attribute name="moduleName" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="signature" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="pos" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="val" type="xs:string"/>
      <xs:attribute name="alias" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="portSpec">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="portSpecItem" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="optional" type="xs:int"/>
      <xs:attribute name="sortKey" type="xs:int"/>
      <xs:attribute name="minConns" type="xs:int"/>
      <xs:attribute name="maxConns" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="abstraction">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="cache" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="namespace" type="xs:string"/>
      <xs:attribute name="package" type="xs:string"/>
      <xs:attribute name="version" type="xs:string"/>
      <xs:attribute name="internalVersion" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="workflow" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="location" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="function" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="cache" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="namespace" type="xs:string"/>
      <xs:attribute name="package" type="xs:string"/>
      <xs:attribute name="version" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="other">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="value" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="key" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="plugin_data">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="data" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="peParameter">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="pos" type="xs:int"/>
      <xs:attribute name="interpolator" type="xs:string"/>
      <xs:attribute name="value" type="xs:string"/>
      <xs:attribute name="dimension" type="xs:int"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="portSpecItem">
    <xs:complexType>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="pos" type="xs:int"/>
      <xs:attribute name="module" type="xs:string"/>
      <xs:attribute name="package" type="xs:string"/>
      <xs:attribute name="namespace" type="xs:string"/>
      <xs:attribute name="label" type="xs:string"/>
      <xs:attribute name="default" type="xs:string"/>
      <xs:attribute name="values" type="xs:string"/>
      <xs:attribute name="entryType" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="workflow">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="connection" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="annotation" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="plugin_data" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="other" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice>
          <xs:element ref="module" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="abstraction" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="group" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="version" type="xs:string"/>
      <xs:attribute name="vistrail_id" type="xs:int"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== lumig242/VisTrailsRecommendation/vistrails_current/vistrails/tests/resources/dummy_new.xml
<?xml version="1.0" ?>
<!--###############################################################################
##
## Copyright (C) 2011-2014, NYU-Poly.
## Copyright (C) 2006-2011, University of Utah. 
## All rights reserved.
## Contact: contact@vistrails.org
##
## This file is part of VisTrails.
##
## "Redistribution and use in source and binary forms, with or without 
## modification, are permitted provided that the following conditions are met:
##
##  - Redistributions of source code must retain the above copyright notice, 
##    this list of conditions and the following disclaimer.
##  - Redistributions in binary form must reproduce the above copyright 
##    notice, this list of conditions and the following disclaimer in the 
##    documentation and/or other materials provided with the distribution.
##  - Neither the name of the University of Utah nor the names of its 
##    contributors may be used to endorse or promote products derived from 
##    this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
## AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
## THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
## PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
## CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
## EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
## PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
## OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
## WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
## OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
## ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
##
###############################################################################
-->
<vistrail dbHost="" dbName="" dbPort="" id="" name="" version="0.5.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vistrails.org/vistrail.xsd">
  <action date="2006-11-09 11:11:45" id="2" prevId="0" user="cscheid">
    <add id="0" objectId="0" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="0" name="File"/>
    </add>
    <add id="1" objectId="0" parentObjId="0" parentObjType="module" what="location">
      <location id="0" x="-0.405904047613" y="0.590405904059"/>
    </add>
  </action>
  <action date="2006-11-09 11:11:49" id="3" prevId="2" user="cscheid">
    <add id="2" objectId="1" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="1" name="String"/>
    </add>
    <add id="3" objectId="1" parentObjId="1" parentObjType="module" what="location">
      <location id="1" x="-79.7416969521" y="113.505537534"/>
    </add>
  </action>
  <action date="2006-11-09 11:11:52" id="4" prevId="3" user="cscheid">
    <add id="4" objectId="0" parentObjId="" parentObjType="" what="connection">
      <connection id="0"/>
    </add>
    <add id="5" objectId="0" parentObjId="0" parentObjType="connection" what="port">
      <port id="0" moduleId="1" moduleName="String" sig="value(String)" type="source"/>
    </add>
    <add id="6" objectId="1" parentObjId="0" parentObjType="connection" what="port">
      <port id="1" moduleId="0" moduleName="File" sig="name(String)" type="destination"/>
    </add>
  </action>
  <action date="2006-11-09 11:12:01" id="5" prevId="4" user="cscheid">
    <add id="7" objectId="2" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="2" name="FileSink"/>
    </add>
    <add id="8" objectId="2" parentObjId="2" parentObjType="module" what="location">
      <location id="2" x="-25.1291511435" y="-88.7084891257"/>
    </add>
  </action>
  <action date="2006-11-09 11:12:04" id="6" prevId="5" user="cscheid">
    <add id="9" objectId="1" parentObjId="" parentObjType="" what="connection">
      <connection id="1"/>
    </add>
    <add id="10" objectId="2" parentObjId="1" parentObjType="connection" what="port">
      <port id="2" moduleId="0" moduleName="File" sig="self(File)" type="source"/>
    </add>
    <add id="11" objectId="3" parentObjId="1" parentObjType="connection" what="port">
      <port id="3" moduleId="2" moduleName="FileSink" sig="file(File)" type="destination"/>
    </add>
  </action>
  <action date="2006-11-09 11:12:06" id="7" prevId="6" user="cscheid">
    <change id="12" newObjId="3" oldObjId="2" parentObjId="2" parentObjType="module" what="location">
      <location id="3" x="63.4317339516" y="-116.014762799"/>
    </change>
  </action>
  <action date="2006-11-09 11:12:06" id="8" prevId="7" user="cscheid">
    <add id="13" objectId="3" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="3" name="String"/>
    </add>
    <add id="14" objectId="4" parentObjId="3" parentObjType="module" what="location">
      <location id="4" x="135.756456779" y="-26.7158678139"/>
    </add>
  </action>
  <action date="2006-11-09 11:12:09" id="9" prevId="8" user="cscheid">
    <add id="15" objectId="2" parentObjId="" parentObjType="" what="connection">
      <connection id="2"/>
    </add>
    <add id="16" objectId="4" parentObjId="2" parentObjType="connection" what="port">
      <port id="4" moduleId="3" moduleName="String" sig="value(String)" type="source"/>
    </add>
    <add id="17" objectId="5" parentObjId="2" parentObjType="connection" what="port">
      <port id="5" moduleId="2" moduleName="FileSink" sig="outputName(String)" type="destination"/>
    </add>
  </action>
  <action date="2006-11-09 11:12:12" id="10" prevId="9" user="cscheid">
    <add id="18" objectId="0" parentObjId="3" parentObjType="module" what="function">
      <function id="0" name="value" pos="0"/>
    </add>
    <add id="19" objectId="0" parentObjId="0" parentObjType="function" what="parameter">
      <parameter alias="" id="0" name="&lt;no description&gt;" pos="0" type="String" val=""/>
    </add>
  </action>
  <action date="2006-11-09 11:12:23" id="11" prevId="10" user="cscheid">
    <change id="20" newObjId="1" oldObjId="0" parentObjId="0" parentObjType="function" what="parameter">
      <parameter alias="" id="1" name="&lt;no description&gt;" pos="0" type="String" val="/tmp/unimportant.tmp"/>
    </change>
  </action>
  <action date="2006-11-21 22:10:52" id="12" prevId="0" user="emanuele">
    <add id="21" objectId="4" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="4" name="Float"/>
    </add>
    <add id="22" objectId="5" parentObjId="4" parentObjType="module" what="location">
      <location id="5" x="-11.8561695459" y="98.7737701549"/>
    </add>
  </action>
  <action date="2006-11-21 22:11:01" id="13" prevId="12" user="emanuele">
    <change id="23" newObjId="6" oldObjId="5" parentObjId="4" parentObjType="module" what="location">
      <location id="6" x="-5.13030019463" y="136.606785107"/>
    </change>
  </action>
  <action date="2006-11-21 22:11:02" id="14" prevId="13" user="emanuele">
    <add id="24" objectId="5" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="5" name="Float"/>
    </add>
    <add id="25" objectId="7" parentObjId="5" parentObjType="module" what="location">
      <location id="7" x="100.802142088" y="40.7631472281"/>
    </add>
  </action>
  <action date="2006-11-21 22:11:06" id="15" prevId="14" user="emanuele">
    <change id="26" newObjId="8" oldObjId="7" parentObjId="5" parentObjType="module" what="location">
      <location id="8" x="76.4208656896" y="14.7004035944"/>
    </change>
  </action>
  <action date="2006-11-21 22:11:06" id="16" prevId="15" user="emanuele">
    <add id="27" objectId="3" parentObjId="" parentObjType="" what="connection">
      <connection id="3"/>
    </add>
    <add id="28" objectId="6" parentObjId="3" parentObjType="connection" what="port">
      <port id="6" moduleId="4" moduleName="Float" sig="value(Float)" type="source"/>
    </add>
    <add id="29" objectId="7" parentObjId="3" parentObjType="connection" what="port">
      <port id="7" moduleId="5" moduleName="Float" sig="value(Float)" type="destination"/>
    </add>
  </action>
  <action date="2006-11-21 22:11:16" id="17" prevId="16" user="emanuele">
    <change id="30" newObjId="9" oldObjId="8" parentObjId="5" parentObjType="module" what="location">
      <location id="9" x="82.306001372" y="8.81526793517"/>
    </change>
    <change id="31" newObjId="10" oldObjId="6" parentObjId="4" parentObjType="module" what="location">
      <location id="10" x="-59.7779886737" y="142.491920766"/>
    </change>
    <change id="32" newObjId="11" oldObjId="9" parentObjId="5" parentObjType="module" what="location">
      <location id="11" x="66.3320616627" y="63.4629561995"/>
    </change>
  </action>
  <action date="2006-11-21 22:11:16" id="18" prevId="17" user="emanuele">
    <add id="33" objectId="6" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="6" name="Float"/>
    </add>
    <add id="34" objectId="12" parentObjId="6" parentObjType="module" what="location">
      <location id="12" x="156.290564236" y="-60.1248926444"/>
    </add>
  </action>
  <action date="2006-11-21 22:11:18" id="19" prevId="18" user="emanuele">
    <add id="35" objectId="4" parentObjId="" parentObjType="" what="connection">
      <connection id="4"/>
    </add>
    <add id="36" objectId="8" parentObjId="4" parentObjType="connection" what="port">
      <port id="8" moduleId="5" moduleName="Float" sig="value(Float)" type="source"/>
    </add>
    <add id="37" objectId="9" parentObjId="4" parentObjType="connection" what="port">
      <port id="9" moduleId="6" moduleName="Float" sig="value(Float)" type="destination"/>
    </add>
  </action>
  <action date="2006-11-21 22:12:06" id="20" prevId="19" user="emanuele">
    <add id="38" objectId="7" parentObjId="" parentObjType="" what="module">
      <module cache="1" id="7" name="Integer"/>
    </add>
